# Generated by Django 4.0.5 on 2022-06-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
